export const UPDATE_SESSIONS_START = 'UPDATE_SESSIONS_START';
export const UPDATE_SESSIONS_COMPLETE = 'UPDATE_SESSIONS_COMPLETE';
export const UPDATE_SESSIONS_ERROR = 'UPDATE_SESSIONS_ERROR';

export const GET_SESSION_START = 'GET_SESSION_START';
export const GET_SESSION_COMPLETE = 'GET_SESSION_COMPLETE';
export const GET_SESSION_ERROR = 'GET_SESSION_ERROR';

export const VIEW_SETTINGS_CHANGED = 'VIEW_SETTINGS_CHANGED';

export const UPDATE_SPEAKER_RATING_START = 'UPDATE_SPEAKER_RATING_START';
export const UPDATE_SPEAKER_RATING_COMPLETE = 'UPDATE_SPEAKER_RATING_COMPLETE';
export const UPDATE_SPEAKER_RATING_ERROR = 'UPDATE_SPEAKER_RATING_ERROR';

export const UPDATE_SPEAKER_BIO_START = 'UPDATE_SPEAKER_BIO_START';
export const UPDATE_SPEAKER_BIO_COMPLETE = 'UPDATE_SPEAKER_BIO_COMPLETE';
export const UPDATE_SPEAKER_BIO_ERROR = 'UPDATE_SPEAKER_BIO_ERROR';

export const GET_CORRESPONDENCE_START = 'GET_CORRESPONDENCE_START';
export const GET_CORRESPONDENCE_COMPLETE = 'GET_CORRESPONDENCE_COMPLETE';
export const GET_CORRESPONDENCE_ERROR = 'GET_CORRESPONDENCE_ERROR';

export const GET_EVENTS_START = 'GET_EVENTS_START';
export const GET_EVENTS_COMPLETE = 'GET_EVENTS_COMPLETE';
export const GET_EVENTS_ERROR = 'GET_EVENTS_ERROR';

export const GET_EVENT_START = 'GET_EVENT_START';
export const GET_EVENT_COMPLETE = 'GET_EVENT_COMPLETE';
export const GET_EVENT_ERROR = 'GET_EVENT_ERROR';

export const SPEAKER_RATING_EDITMODE_CHANGED = 'SPEAKER_RATING_EDITMODE_CHANGED';
export const SPEAKER_BIO_EDITMODE_CHANGED = 'SPEAKER_BIO_EDITMODE_CHANGED';

export const SPEAKER_RATING_STASH_CHANGED = 'SPEAKER_RATING_STASH_CHANGED';
export const SPEAKER_BIO_STASH_CHANGED = 'SPEAKER_BIO_STASH_CHANGED';
