export const UPDATE_SESSIONS_START = 'UPDATE_SESSIONS_START';
export const UPDATE_SESSIONS_COMPLETE = 'UPDATE_SESSIONS_COMPLETE';
export const UPDATE_SESSIONS_ERROR = 'UPDATE_SESSIONS_ERROR';

export const UPDATE_LAST_CONTACT_START = 'UPDATE_LAST_CONTACT_START';
export const UPDATE_LAST_CONTACT_COMPLETE = 'UPDATE_LAST_CONTACT_COMPLETE';
export const UPDATE_LAST_CONTACT_ERROR = 'UPDATE_LAST_CONTACT_ERROR';

export const GET_SESSION_START = 'GET_SESSION_START';
export const GET_SESSION_COMPLETE = 'GET_SESSION_COMPLETE';
export const GET_SESSION_ERROR = 'GET_SESSION_ERROR';

export const GET_PROFILES_START = 'GET_PROFILES_START';
export const GET_PROFILES_COMPLETE = 'GET_PROFILES_COMPLETE';
export const GET_PROFILES_ERROR = 'GET_PROFILES_ERROR';

export const VIEW_SETTINGS_CHANGED = 'VIEW_SETTINGS_CHANGED';
