export const UPDATE_SESSIONS_START = 'UPDATE_SESSIONS_START';
export const UPDATE_SESSIONS_COMPLETE = 'UPDATE_SESSIONS_COMPLETE';
export const UPDATE_SESSIONS_ERROR = 'UPDATE_SESSIONS_ERROR';

export const GET_SESSION_START = 'GET_SESSION_START';
export const GET_SESSION_COMPLETE = 'GET_SESSION_COMPLETE';
export const GET_SESSION_ERROR = 'GET_SESSION_ERROR';

export const UPDATE_SESSION_DESCRIPTION_START = 'UPDATE_SESSION_DESCRIPTION_START';
export const UPDATE_SESSION_DESCRIPTION_COMPLETE = 'UPDATE_SESSION_DESCRIPTION_COMPLETE';
export const UPDATE_SESSION_DESCRIPTION_ERROR = 'UPDATE_SESSION_DESCRIPTION_ERROR';

export const VIEW_SETTINGS_CHANGED = 'VIEW_SETTINGS_CHANGED';

export const UPDATE_SPEAKER_RATING_START = 'UPDATE_SPEAKER_RATING_START';
export const UPDATE_SPEAKER_RATING_COMPLETE = 'UPDATE_SPEAKER_RATING_COMPLETE';
export const UPDATE_SPEAKER_RATING_ERROR = 'UPDATE_SPEAKER_RATING_ERROR';

export const UPDATE_SPEAKER_BIO_START = 'UPDATE_SPEAKER_BIO_START';
export const UPDATE_SPEAKER_BIO_COMPLETE = 'UPDATE_SPEAKER_BIO_COMPLETE';
export const UPDATE_SPEAKER_BIO_ERROR = 'UPDATE_SPEAKER_BIO_ERROR';

export const GET_CORRESPONDENCE_START = 'GET_CORRESPONDENCE_START';
export const GET_CORRESPONDENCE_COMPLETE = 'GET_CORRESPONDENCE_COMPLETE';
export const GET_CORRESPONDENCE_ERROR = 'GET_CORRESPONDENCE_ERROR';

export const GET_EVENTS_START = 'GET_EVENTS_START';
export const GET_EVENTS_COMPLETE = 'GET_EVENTS_COMPLETE';
export const GET_EVENTS_ERROR = 'GET_EVENTS_ERROR';

export const GET_EVENT_START = 'GET_EVENT_START';
export const GET_EVENT_COMPLETE = 'GET_EVENT_COMPLETE';
export const GET_EVENT_ERROR = 'GET_EVENT_ERROR';

export const SESSION_VIEW_EDITMODE_CHANGED = 'SESSION_VIEW_EDITMODE_CHANGED';

export const SESSION_VIEW_EDITSTASH_CHANGED = 'SESSION_VIEW_EDITSTASH_CHANGED';
