resource_types:
  - name: ecs
    type: docker-image
    source:
      repository: bristechsrm/notify_ecs

jobs:
- name: build
  public: true
  serial: true
  plan:
  - get: code
    trigger: true
  - task: build
    file: code/concourse/build.yml
  - task: create-context
    file: code/concourse/create-context.yml
  - put: image
    params:
      build: context

resources:
- name: code
  type: git
  source:
    uri: https://github.com/BristechSRM/frontend.git
    branch: concourse

- name: image
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: bristechsrm
    password: {{docker-hub-password}}
    repository: bristechsrm/frontend

- name: cluster
  type: ecs
  source:
    stackName: development
    clusterName: frontCluster
    taskName: frontTaskDefinition
    serviceName: frontService
    accessKeyId: {{awsAccessKeyId}}
    secretAccessKey: {{awsSecretAccessKey}}
