resource_types:
  - name: docker-swarm-deploy
    type: docker-image
    source:
      repository: bristechsrm/docker-swarm-deploy

jobs:
- name: build
  public: true
  serial: true
  plan:
  - get: code
    trigger: true
  - task: build
    file: code/concourse/build.yml
  - task: create-context
    file: code/concourse/create-context.yml
  - put: image
    params:
      build: context
  - put: swarm

resources:
- name: code
  type: git
  source:
    uri: https://github.com/BristechSRM/frontend.git
    branch: master

- name: image
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: bristechsrm
    password: {{docker-hub-password}}
    repository: bristechsrm/frontend

- name: swarm
  type: docker-swarm-deploy
  source:
    serviceName: frontend
    executableName: frontend
    nodeName: {{frontendNode}}
    portNumber: 80
    repository: bristechsrm/frontend
    swarmMasterIp: {{swarmMasterIp}}
    network: bridge
